/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kubernetes);
  }
}(this, function(expect, Kubernetes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kubernetes.ApiextensionsV1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiextensionsV1Api', function() {
    describe('createApiextensionsV1CustomResourceDefinition', function() {
      it('should call createApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test createApiextensionsV1CustomResourceDefinition
        //instance.createApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteApiextensionsV1CollectionCustomResourceDefinition', function() {
      it('should call deleteApiextensionsV1CollectionCustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test deleteApiextensionsV1CollectionCustomResourceDefinition
        //instance.deleteApiextensionsV1CollectionCustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteApiextensionsV1CustomResourceDefinition', function() {
      it('should call deleteApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test deleteApiextensionsV1CustomResourceDefinition
        //instance.deleteApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getApiextensionsV1APIResources', function() {
      it('should call getApiextensionsV1APIResources successfully', function(done) {
        //uncomment below and update the code to test getApiextensionsV1APIResources
        //instance.getApiextensionsV1APIResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listApiextensionsV1CustomResourceDefinition', function() {
      it('should call listApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test listApiextensionsV1CustomResourceDefinition
        //instance.listApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchApiextensionsV1CustomResourceDefinition', function() {
      it('should call patchApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test patchApiextensionsV1CustomResourceDefinition
        //instance.patchApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchApiextensionsV1CustomResourceDefinitionStatus', function() {
      it('should call patchApiextensionsV1CustomResourceDefinitionStatus successfully', function(done) {
        //uncomment below and update the code to test patchApiextensionsV1CustomResourceDefinitionStatus
        //instance.patchApiextensionsV1CustomResourceDefinitionStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readApiextensionsV1CustomResourceDefinition', function() {
      it('should call readApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test readApiextensionsV1CustomResourceDefinition
        //instance.readApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readApiextensionsV1CustomResourceDefinitionStatus', function() {
      it('should call readApiextensionsV1CustomResourceDefinitionStatus successfully', function(done) {
        //uncomment below and update the code to test readApiextensionsV1CustomResourceDefinitionStatus
        //instance.readApiextensionsV1CustomResourceDefinitionStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceApiextensionsV1CustomResourceDefinition', function() {
      it('should call replaceApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test replaceApiextensionsV1CustomResourceDefinition
        //instance.replaceApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceApiextensionsV1CustomResourceDefinitionStatus', function() {
      it('should call replaceApiextensionsV1CustomResourceDefinitionStatus successfully', function(done) {
        //uncomment below and update the code to test replaceApiextensionsV1CustomResourceDefinitionStatus
        //instance.replaceApiextensionsV1CustomResourceDefinitionStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchApiextensionsV1CustomResourceDefinition', function() {
      it('should call watchApiextensionsV1CustomResourceDefinition successfully', function(done) {
        //uncomment below and update the code to test watchApiextensionsV1CustomResourceDefinition
        //instance.watchApiextensionsV1CustomResourceDefinition(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchApiextensionsV1CustomResourceDefinitionList', function() {
      it('should call watchApiextensionsV1CustomResourceDefinitionList successfully', function(done) {
        //uncomment below and update the code to test watchApiextensionsV1CustomResourceDefinitionList
        //instance.watchApiextensionsV1CustomResourceDefinitionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
