/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kubernetes);
  }
}(this, function(expect, Kubernetes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kubernetes.AutoscalingV2Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AutoscalingV2Api', function() {
    describe('createAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call createAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test createAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.createAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler', function() {
      it('should call deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler
        //instance.deleteAutoscalingV2CollectionNamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call deleteAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test deleteAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.deleteAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAutoscalingV2APIResources', function() {
      it('should call getAutoscalingV2APIResources successfully', function(done) {
        //uncomment below and update the code to test getAutoscalingV2APIResources
        //instance.getAutoscalingV2APIResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAutoscalingV2HorizontalPodAutoscalerForAllNamespaces', function() {
      it('should call listAutoscalingV2HorizontalPodAutoscalerForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test listAutoscalingV2HorizontalPodAutoscalerForAllNamespaces
        //instance.listAutoscalingV2HorizontalPodAutoscalerForAllNamespaces(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call listAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test listAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.listAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call patchAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test patchAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.patchAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus', function() {
      it('should call patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus successfully', function(done) {
        //uncomment below and update the code to test patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus
        //instance.patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call readAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test readAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.readAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus', function() {
      it('should call readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus successfully', function(done) {
        //uncomment below and update the code to test readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus
        //instance.readAutoscalingV2NamespacedHorizontalPodAutoscalerStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call replaceAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test replaceAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.replaceAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus', function() {
      it('should call replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus successfully', function(done) {
        //uncomment below and update the code to test replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus
        //instance.replaceAutoscalingV2NamespacedHorizontalPodAutoscalerStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces', function() {
      it('should call watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces
        //instance.watchAutoscalingV2HorizontalPodAutoscalerListForAllNamespaces(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchAutoscalingV2NamespacedHorizontalPodAutoscaler', function() {
      it('should call watchAutoscalingV2NamespacedHorizontalPodAutoscaler successfully', function(done) {
        //uncomment below and update the code to test watchAutoscalingV2NamespacedHorizontalPodAutoscaler
        //instance.watchAutoscalingV2NamespacedHorizontalPodAutoscaler(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchAutoscalingV2NamespacedHorizontalPodAutoscalerList', function() {
      it('should call watchAutoscalingV2NamespacedHorizontalPodAutoscalerList successfully', function(done) {
        //uncomment below and update the code to test watchAutoscalingV2NamespacedHorizontalPodAutoscalerList
        //instance.watchAutoscalingV2NamespacedHorizontalPodAutoscalerList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
