/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kubernetes);
  }
}(this, function(expect, Kubernetes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kubernetes.DiscoveryV1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DiscoveryV1Api', function() {
    describe('createDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call createDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test createDiscoveryV1NamespacedEndpointSlice
        //instance.createDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDiscoveryV1CollectionNamespacedEndpointSlice', function() {
      it('should call deleteDiscoveryV1CollectionNamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test deleteDiscoveryV1CollectionNamespacedEndpointSlice
        //instance.deleteDiscoveryV1CollectionNamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call deleteDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test deleteDiscoveryV1NamespacedEndpointSlice
        //instance.deleteDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDiscoveryV1APIResources', function() {
      it('should call getDiscoveryV1APIResources successfully', function(done) {
        //uncomment below and update the code to test getDiscoveryV1APIResources
        //instance.getDiscoveryV1APIResources(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDiscoveryV1EndpointSliceForAllNamespaces', function() {
      it('should call listDiscoveryV1EndpointSliceForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test listDiscoveryV1EndpointSliceForAllNamespaces
        //instance.listDiscoveryV1EndpointSliceForAllNamespaces(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call listDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test listDiscoveryV1NamespacedEndpointSlice
        //instance.listDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call patchDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test patchDiscoveryV1NamespacedEndpointSlice
        //instance.patchDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call readDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test readDiscoveryV1NamespacedEndpointSlice
        //instance.readDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call replaceDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test replaceDiscoveryV1NamespacedEndpointSlice
        //instance.replaceDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchDiscoveryV1EndpointSliceListForAllNamespaces', function() {
      it('should call watchDiscoveryV1EndpointSliceListForAllNamespaces successfully', function(done) {
        //uncomment below and update the code to test watchDiscoveryV1EndpointSliceListForAllNamespaces
        //instance.watchDiscoveryV1EndpointSliceListForAllNamespaces(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchDiscoveryV1NamespacedEndpointSlice', function() {
      it('should call watchDiscoveryV1NamespacedEndpointSlice successfully', function(done) {
        //uncomment below and update the code to test watchDiscoveryV1NamespacedEndpointSlice
        //instance.watchDiscoveryV1NamespacedEndpointSlice(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('watchDiscoveryV1NamespacedEndpointSliceList', function() {
      it('should call watchDiscoveryV1NamespacedEndpointSliceList successfully', function(done) {
        //uncomment below and update the code to test watchDiscoveryV1NamespacedEndpointSliceList
        //instance.watchDiscoveryV1NamespacedEndpointSliceList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
