/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kubernetes);
  }
}(this, function(expect, Kubernetes) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kubernetes.NodeinfoVolcanoShV1alpha1Api();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NodeinfoVolcanoShV1alpha1Api', function() {
    describe('createNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call createNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test createNodeinfoVolcanoShV1alpha1Numatopology
        //instance.createNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNodeinfoVolcanoShV1alpha1CollectionNumatopology', function() {
      it('should call deleteNodeinfoVolcanoShV1alpha1CollectionNumatopology successfully', function(done) {
        //uncomment below and update the code to test deleteNodeinfoVolcanoShV1alpha1CollectionNumatopology
        //instance.deleteNodeinfoVolcanoShV1alpha1CollectionNumatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call deleteNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test deleteNodeinfoVolcanoShV1alpha1Numatopology
        //instance.deleteNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call listNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test listNodeinfoVolcanoShV1alpha1Numatopology
        //instance.listNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call patchNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test patchNodeinfoVolcanoShV1alpha1Numatopology
        //instance.patchNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call readNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test readNodeinfoVolcanoShV1alpha1Numatopology
        //instance.readNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceNodeinfoVolcanoShV1alpha1Numatopology', function() {
      it('should call replaceNodeinfoVolcanoShV1alpha1Numatopology successfully', function(done) {
        //uncomment below and update the code to test replaceNodeinfoVolcanoShV1alpha1Numatopology
        //instance.replaceNodeinfoVolcanoShV1alpha1Numatopology(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
