/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiCoreV1NodeRuntimeHandlerFeatures from './IoK8sApiCoreV1NodeRuntimeHandlerFeatures';

/**
 * The IoK8sApiCoreV1NodeRuntimeHandler model module.
 * @module model/IoK8sApiCoreV1NodeRuntimeHandler
 * @version v1.30.0
 */
class IoK8sApiCoreV1NodeRuntimeHandler {
    /**
     * Constructs a new <code>IoK8sApiCoreV1NodeRuntimeHandler</code>.
     * NodeRuntimeHandler is a set of runtime handler information.
     * @alias module:model/IoK8sApiCoreV1NodeRuntimeHandler
     */
    constructor() { 
        
        IoK8sApiCoreV1NodeRuntimeHandler.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1NodeRuntimeHandler</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1NodeRuntimeHandler} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1NodeRuntimeHandler} The populated <code>IoK8sApiCoreV1NodeRuntimeHandler</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1NodeRuntimeHandler();

            if (data.hasOwnProperty('features')) {
                obj['features'] = IoK8sApiCoreV1NodeRuntimeHandlerFeatures.constructFromObject(data['features']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1NodeRuntimeHandler</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1NodeRuntimeHandler</code>.
     */
    static validateJSON(data) {
        // validate the optional field `features`
        if (data['features']) { // data not null
          IoK8sApiCoreV1NodeRuntimeHandlerFeatures.validateJSON(data['features']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {module:model/IoK8sApiCoreV1NodeRuntimeHandlerFeatures} features
 */
IoK8sApiCoreV1NodeRuntimeHandler.prototype['features'] = undefined;

/**
 * Runtime handler name. Empty for the default runtime handler.
 * @member {String} name
 */
IoK8sApiCoreV1NodeRuntimeHandler.prototype['name'] = undefined;






export default IoK8sApiCoreV1NodeRuntimeHandler;

