/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiCoreV1LocalObjectReference from './IoK8sApiCoreV1LocalObjectReference';

/**
 * The IoK8sApiCoreV1CSIVolumeSource model module.
 * @module model/IoK8sApiCoreV1CSIVolumeSource
 * @version v1.30.0
 */
class IoK8sApiCoreV1CSIVolumeSource {
    /**
     * Constructs a new <code>IoK8sApiCoreV1CSIVolumeSource</code>.
     * Represents a source location of a volume to mount, managed by an external CSI driver
     * @alias module:model/IoK8sApiCoreV1CSIVolumeSource
     * @param driver {String} driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
     */
    constructor(driver) { 
        
        IoK8sApiCoreV1CSIVolumeSource.initialize(this, driver);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, driver) { 
        obj['driver'] = driver;
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1CSIVolumeSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1CSIVolumeSource} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1CSIVolumeSource} The populated <code>IoK8sApiCoreV1CSIVolumeSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1CSIVolumeSource();

            if (data.hasOwnProperty('driver')) {
                obj['driver'] = ApiClient.convertToType(data['driver'], 'String');
            }
            if (data.hasOwnProperty('fsType')) {
                obj['fsType'] = ApiClient.convertToType(data['fsType'], 'String');
            }
            if (data.hasOwnProperty('nodePublishSecretRef')) {
                obj['nodePublishSecretRef'] = IoK8sApiCoreV1LocalObjectReference.constructFromObject(data['nodePublishSecretRef']);
            }
            if (data.hasOwnProperty('readOnly')) {
                obj['readOnly'] = ApiClient.convertToType(data['readOnly'], 'Boolean');
            }
            if (data.hasOwnProperty('volumeAttributes')) {
                obj['volumeAttributes'] = ApiClient.convertToType(data['volumeAttributes'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1CSIVolumeSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1CSIVolumeSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApiCoreV1CSIVolumeSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['driver'] && !(typeof data['driver'] === 'string' || data['driver'] instanceof String)) {
            throw new Error("Expected the field `driver` to be a primitive type in the JSON string but got " + data['driver']);
        }
        // ensure the json data is a string
        if (data['fsType'] && !(typeof data['fsType'] === 'string' || data['fsType'] instanceof String)) {
            throw new Error("Expected the field `fsType` to be a primitive type in the JSON string but got " + data['fsType']);
        }
        // validate the optional field `nodePublishSecretRef`
        if (data['nodePublishSecretRef']) { // data not null
          IoK8sApiCoreV1LocalObjectReference.validateJSON(data['nodePublishSecretRef']);
        }

        return true;
    }


}

IoK8sApiCoreV1CSIVolumeSource.RequiredProperties = ["driver"];

/**
 * driver is the name of the CSI driver that handles this volume. Consult with your admin for the correct name as registered in the cluster.
 * @member {String} driver
 */
IoK8sApiCoreV1CSIVolumeSource.prototype['driver'] = undefined;

/**
 * fsType to mount. Ex. \"ext4\", \"xfs\", \"ntfs\". If not provided, the empty value is passed to the associated CSI driver which will determine the default filesystem to apply.
 * @member {String} fsType
 */
IoK8sApiCoreV1CSIVolumeSource.prototype['fsType'] = undefined;

/**
 * @member {module:model/IoK8sApiCoreV1LocalObjectReference} nodePublishSecretRef
 */
IoK8sApiCoreV1CSIVolumeSource.prototype['nodePublishSecretRef'] = undefined;

/**
 * readOnly specifies a read-only configuration for the volume. Defaults to false (read/write).
 * @member {Boolean} readOnly
 */
IoK8sApiCoreV1CSIVolumeSource.prototype['readOnly'] = undefined;

/**
 * volumeAttributes stores driver-specific properties that are passed to the CSI driver. Consult your driver's documentation for supported values.
 * @member {Object.<String, String>} volumeAttributes
 */
IoK8sApiCoreV1CSIVolumeSource.prototype['volumeAttributes'] = undefined;






export default IoK8sApiCoreV1CSIVolumeSource;

