/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiAuthorizationV1NonResourceAttributes from './IoK8sApiAuthorizationV1NonResourceAttributes';
import IoK8sApiAuthorizationV1ResourceAttributes from './IoK8sApiAuthorizationV1ResourceAttributes';

/**
 * The IoK8sApiAuthorizationV1SubjectAccessReviewSpec model module.
 * @module model/IoK8sApiAuthorizationV1SubjectAccessReviewSpec
 * @version v1.30.0
 */
class IoK8sApiAuthorizationV1SubjectAccessReviewSpec {
    /**
     * Constructs a new <code>IoK8sApiAuthorizationV1SubjectAccessReviewSpec</code>.
     * SubjectAccessReviewSpec is a description of the access request.  Exactly one of ResourceAuthorizationAttributes and NonResourceAuthorizationAttributes must be set
     * @alias module:model/IoK8sApiAuthorizationV1SubjectAccessReviewSpec
     */
    constructor() { 
        
        IoK8sApiAuthorizationV1SubjectAccessReviewSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiAuthorizationV1SubjectAccessReviewSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiAuthorizationV1SubjectAccessReviewSpec} obj Optional instance to populate.
     * @return {module:model/IoK8sApiAuthorizationV1SubjectAccessReviewSpec} The populated <code>IoK8sApiAuthorizationV1SubjectAccessReviewSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiAuthorizationV1SubjectAccessReviewSpec();

            if (data.hasOwnProperty('extra')) {
                obj['extra'] = ApiClient.convertToType(data['extra'], {'String': ['String']});
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], ['String']);
            }
            if (data.hasOwnProperty('nonResourceAttributes')) {
                obj['nonResourceAttributes'] = IoK8sApiAuthorizationV1NonResourceAttributes.constructFromObject(data['nonResourceAttributes']);
            }
            if (data.hasOwnProperty('resourceAttributes')) {
                obj['resourceAttributes'] = IoK8sApiAuthorizationV1ResourceAttributes.constructFromObject(data['resourceAttributes']);
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiAuthorizationV1SubjectAccessReviewSpec</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiAuthorizationV1SubjectAccessReviewSpec</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['groups'])) {
            throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
        }
        // validate the optional field `nonResourceAttributes`
        if (data['nonResourceAttributes']) { // data not null
          IoK8sApiAuthorizationV1NonResourceAttributes.validateJSON(data['nonResourceAttributes']);
        }
        // validate the optional field `resourceAttributes`
        if (data['resourceAttributes']) { // data not null
          IoK8sApiAuthorizationV1ResourceAttributes.validateJSON(data['resourceAttributes']);
        }
        // ensure the json data is a string
        if (data['uid'] && !(typeof data['uid'] === 'string' || data['uid'] instanceof String)) {
            throw new Error("Expected the field `uid` to be a primitive type in the JSON string but got " + data['uid']);
        }
        // ensure the json data is a string
        if (data['user'] && !(typeof data['user'] === 'string' || data['user'] instanceof String)) {
            throw new Error("Expected the field `user` to be a primitive type in the JSON string but got " + data['user']);
        }

        return true;
    }


}



/**
 * Extra corresponds to the user.Info.GetExtra() method from the authenticator.  Since that is input to the authorizer it needs a reflection here.
 * @member {Object.<String, Array.<String>>} extra
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['extra'] = undefined;

/**
 * Groups is the groups you're testing for.
 * @member {Array.<String>} groups
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['groups'] = undefined;

/**
 * @member {module:model/IoK8sApiAuthorizationV1NonResourceAttributes} nonResourceAttributes
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['nonResourceAttributes'] = undefined;

/**
 * @member {module:model/IoK8sApiAuthorizationV1ResourceAttributes} resourceAttributes
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['resourceAttributes'] = undefined;

/**
 * UID information about the requesting user.
 * @member {String} uid
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['uid'] = undefined;

/**
 * User is the user you're testing for. If you specify \"User\" but not \"Groups\", then is it interpreted as \"What if User were not a member of any groups
 * @member {String} user
 */
IoK8sApiAuthorizationV1SubjectAccessReviewSpec.prototype['user'] = undefined;






export default IoK8sApiAuthorizationV1SubjectAccessReviewSpec;

