/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiCoreV1ConfigMapNodeConfigSource from './IoK8sApiCoreV1ConfigMapNodeConfigSource';

/**
 * The IoK8sApiCoreV1NodeConfigSource model module.
 * @module model/IoK8sApiCoreV1NodeConfigSource
 * @version v1.30.0
 */
class IoK8sApiCoreV1NodeConfigSource {
    /**
     * Constructs a new <code>IoK8sApiCoreV1NodeConfigSource</code>.
     * NodeConfigSource specifies a source of node configuration. Exactly one subfield (excluding metadata) must be non-nil. This API is deprecated since 1.22
     * @alias module:model/IoK8sApiCoreV1NodeConfigSource
     */
    constructor() { 
        
        IoK8sApiCoreV1NodeConfigSource.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1NodeConfigSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1NodeConfigSource} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1NodeConfigSource} The populated <code>IoK8sApiCoreV1NodeConfigSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1NodeConfigSource();

            if (data.hasOwnProperty('configMap')) {
                obj['configMap'] = IoK8sApiCoreV1ConfigMapNodeConfigSource.constructFromObject(data['configMap']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1NodeConfigSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1NodeConfigSource</code>.
     */
    static validateJSON(data) {
        // validate the optional field `configMap`
        if (data['configMap']) { // data not null
          IoK8sApiCoreV1ConfigMapNodeConfigSource.validateJSON(data['configMap']);
        }

        return true;
    }


}



/**
 * @member {module:model/IoK8sApiCoreV1ConfigMapNodeConfigSource} configMap
 */
IoK8sApiCoreV1NodeConfigSource.prototype['configMap'] = undefined;






export default IoK8sApiCoreV1NodeConfigSource;

