/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IoK8sApiCoreV1ContainerImage model module.
 * @module model/IoK8sApiCoreV1ContainerImage
 * @version v1.30.0
 */
class IoK8sApiCoreV1ContainerImage {
    /**
     * Constructs a new <code>IoK8sApiCoreV1ContainerImage</code>.
     * Describe a container image
     * @alias module:model/IoK8sApiCoreV1ContainerImage
     */
    constructor() { 
        
        IoK8sApiCoreV1ContainerImage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1ContainerImage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1ContainerImage} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1ContainerImage} The populated <code>IoK8sApiCoreV1ContainerImage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1ContainerImage();

            if (data.hasOwnProperty('names')) {
                obj['names'] = ApiClient.convertToType(data['names'], ['String']);
            }
            if (data.hasOwnProperty('sizeBytes')) {
                obj['sizeBytes'] = ApiClient.convertToType(data['sizeBytes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1ContainerImage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1ContainerImage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['names'])) {
            throw new Error("Expected the field `names` to be an array in the JSON data but got " + data['names']);
        }

        return true;
    }


}



/**
 * Names by which this image is known. e.g. [\"kubernetes.example/hyperkube:v1.0.7\", \"cloud-vendor.registry.example/cloud-vendor/hyperkube:v1.0.7\"]
 * @member {Array.<String>} names
 */
IoK8sApiCoreV1ContainerImage.prototype['names'] = undefined;

/**
 * The size of the image in bytes.
 * @member {Number} sizeBytes
 */
IoK8sApiCoreV1ContainerImage.prototype['sizeBytes'] = undefined;






export default IoK8sApiCoreV1ContainerImage;

