/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiNetworkingV1NetworkPolicyPeer from './IoK8sApiNetworkingV1NetworkPolicyPeer';
import IoK8sApiNetworkingV1NetworkPolicyPort from './IoK8sApiNetworkingV1NetworkPolicyPort';

/**
 * The IoK8sApiNetworkingV1NetworkPolicyEgressRule model module.
 * @module model/IoK8sApiNetworkingV1NetworkPolicyEgressRule
 * @version v1.30.0
 */
class IoK8sApiNetworkingV1NetworkPolicyEgressRule {
    /**
     * Constructs a new <code>IoK8sApiNetworkingV1NetworkPolicyEgressRule</code>.
     * NetworkPolicyEgressRule describes a particular set of traffic that is allowed out of pods matched by a NetworkPolicySpec&#39;s podSelector. The traffic must match both ports and to. This type is beta-level in 1.8
     * @alias module:model/IoK8sApiNetworkingV1NetworkPolicyEgressRule
     */
    constructor() { 
        
        IoK8sApiNetworkingV1NetworkPolicyEgressRule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiNetworkingV1NetworkPolicyEgressRule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiNetworkingV1NetworkPolicyEgressRule} obj Optional instance to populate.
     * @return {module:model/IoK8sApiNetworkingV1NetworkPolicyEgressRule} The populated <code>IoK8sApiNetworkingV1NetworkPolicyEgressRule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiNetworkingV1NetworkPolicyEgressRule();

            if (data.hasOwnProperty('ports')) {
                obj['ports'] = ApiClient.convertToType(data['ports'], [IoK8sApiNetworkingV1NetworkPolicyPort]);
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], [IoK8sApiNetworkingV1NetworkPolicyPeer]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiNetworkingV1NetworkPolicyEgressRule</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiNetworkingV1NetworkPolicyEgressRule</code>.
     */
    static validateJSON(data) {
        if (data['ports']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ports'])) {
                throw new Error("Expected the field `ports` to be an array in the JSON data but got " + data['ports']);
            }
            // validate the optional field `ports` (array)
            for (const item of data['ports']) {
                IoK8sApiNetworkingV1NetworkPolicyPort.validateJSON(item);
            };
        }
        if (data['to']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['to'])) {
                throw new Error("Expected the field `to` to be an array in the JSON data but got " + data['to']);
            }
            // validate the optional field `to` (array)
            for (const item of data['to']) {
                IoK8sApiNetworkingV1NetworkPolicyPeer.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * ports is a list of destination ports for outgoing traffic. Each item in this list is combined using a logical OR. If this field is empty or missing, this rule matches all ports (traffic not restricted by port). If this field is present and contains at least one item, then this rule allows traffic only if the traffic matches at least one port in the list.
 * @member {Array.<module:model/IoK8sApiNetworkingV1NetworkPolicyPort>} ports
 */
IoK8sApiNetworkingV1NetworkPolicyEgressRule.prototype['ports'] = undefined;

/**
 * to is a list of destinations for outgoing traffic of pods selected for this rule. Items in this list are combined using a logical OR operation. If this field is empty or missing, this rule matches all destinations (traffic not restricted by destination). If this field is present and contains at least one item, this rule allows traffic only if the traffic matches at least one item in the to list.
 * @member {Array.<module:model/IoK8sApiNetworkingV1NetworkPolicyPeer>} to
 */
IoK8sApiNetworkingV1NetworkPolicyEgressRule.prototype['to'] = undefined;






export default IoK8sApiNetworkingV1NetworkPolicyEgressRule;

