/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale model module.
 * @module model/IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale
 * @version v1.30.0
 */
class IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale {
    /**
     * Constructs a new <code>IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale</code>.
     * CustomResourceSubresourceScale defines how to serve the scale subresource for CustomResources.
     * @alias module:model/IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale
     * @param specReplicasPath {String} specReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `spec.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.spec`. If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.
     * @param statusReplicasPath {String} statusReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `status.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status`. If there is no value under the given path in the custom resource, the `status.replicas` value in the `/scale` subresource will default to 0.
     */
    constructor(specReplicasPath, statusReplicasPath) { 
        
        IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.initialize(this, specReplicasPath, statusReplicasPath);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, specReplicasPath, statusReplicasPath) { 
        obj['specReplicasPath'] = specReplicasPath;
        obj['statusReplicasPath'] = statusReplicasPath;
    }

    /**
     * Constructs a <code>IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale} obj Optional instance to populate.
     * @return {module:model/IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale} The populated <code>IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale();

            if (data.hasOwnProperty('labelSelectorPath')) {
                obj['labelSelectorPath'] = ApiClient.convertToType(data['labelSelectorPath'], 'String');
            }
            if (data.hasOwnProperty('specReplicasPath')) {
                obj['specReplicasPath'] = ApiClient.convertToType(data['specReplicasPath'], 'String');
            }
            if (data.hasOwnProperty('statusReplicasPath')) {
                obj['statusReplicasPath'] = ApiClient.convertToType(data['statusReplicasPath'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['labelSelectorPath'] && !(typeof data['labelSelectorPath'] === 'string' || data['labelSelectorPath'] instanceof String)) {
            throw new Error("Expected the field `labelSelectorPath` to be a primitive type in the JSON string but got " + data['labelSelectorPath']);
        }
        // ensure the json data is a string
        if (data['specReplicasPath'] && !(typeof data['specReplicasPath'] === 'string' || data['specReplicasPath'] instanceof String)) {
            throw new Error("Expected the field `specReplicasPath` to be a primitive type in the JSON string but got " + data['specReplicasPath']);
        }
        // ensure the json data is a string
        if (data['statusReplicasPath'] && !(typeof data['statusReplicasPath'] === 'string' || data['statusReplicasPath'] instanceof String)) {
            throw new Error("Expected the field `statusReplicasPath` to be a primitive type in the JSON string but got " + data['statusReplicasPath']);
        }

        return true;
    }


}

IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.RequiredProperties = ["specReplicasPath", "statusReplicasPath"];

/**
 * labelSelectorPath defines the JSON path inside of a custom resource that corresponds to Scale `status.selector`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status` or `.spec`. Must be set to work with HorizontalPodAutoscaler. The field pointed by this JSON path must be a string field (not a complex selector struct) which contains a serialized label selector in string form. More info: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions#scale-subresource If there is no value under the given path in the custom resource, the `status.selector` value in the `/scale` subresource will default to the empty string.
 * @member {String} labelSelectorPath
 */
IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.prototype['labelSelectorPath'] = undefined;

/**
 * specReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `spec.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.spec`. If there is no value under the given path in the custom resource, the `/scale` subresource will return an error on GET.
 * @member {String} specReplicasPath
 */
IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.prototype['specReplicasPath'] = undefined;

/**
 * statusReplicasPath defines the JSON path inside of a custom resource that corresponds to Scale `status.replicas`. Only JSON paths without the array notation are allowed. Must be a JSON Path under `.status`. If there is no value under the given path in the custom resource, the `status.replicas` value in the `/scale` subresource will default to 0.
 * @member {String} statusReplicasPath
 */
IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale.prototype['statusReplicasPath'] = undefined;






export default IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale;

