/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IoK8sApiCoreV1NodeRuntimeHandlerFeatures model module.
 * @module model/IoK8sApiCoreV1NodeRuntimeHandlerFeatures
 * @version v1.30.0
 */
class IoK8sApiCoreV1NodeRuntimeHandlerFeatures {
    /**
     * Constructs a new <code>IoK8sApiCoreV1NodeRuntimeHandlerFeatures</code>.
     * NodeRuntimeHandlerFeatures is a set of runtime features.
     * @alias module:model/IoK8sApiCoreV1NodeRuntimeHandlerFeatures
     */
    constructor() { 
        
        IoK8sApiCoreV1NodeRuntimeHandlerFeatures.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1NodeRuntimeHandlerFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1NodeRuntimeHandlerFeatures} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1NodeRuntimeHandlerFeatures} The populated <code>IoK8sApiCoreV1NodeRuntimeHandlerFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1NodeRuntimeHandlerFeatures();

            if (data.hasOwnProperty('recursiveReadOnlyMounts')) {
                obj['recursiveReadOnlyMounts'] = ApiClient.convertToType(data['recursiveReadOnlyMounts'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1NodeRuntimeHandlerFeatures</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1NodeRuntimeHandlerFeatures</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * RecursiveReadOnlyMounts is set to true if the runtime handler supports RecursiveReadOnlyMounts.
 * @member {Boolean} recursiveReadOnlyMounts
 */
IoK8sApiCoreV1NodeRuntimeHandlerFeatures.prototype['recursiveReadOnlyMounts'] = undefined;






export default IoK8sApiCoreV1NodeRuntimeHandlerFeatures;

