/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiFlowcontrolV1beta3QueuingConfiguration from './IoK8sApiFlowcontrolV1beta3QueuingConfiguration';

/**
 * The IoK8sApiFlowcontrolV1beta3LimitResponse model module.
 * @module model/IoK8sApiFlowcontrolV1beta3LimitResponse
 * @version v1.30.0
 */
class IoK8sApiFlowcontrolV1beta3LimitResponse {
    /**
     * Constructs a new <code>IoK8sApiFlowcontrolV1beta3LimitResponse</code>.
     * LimitResponse defines how to handle requests that can not be executed right now.
     * @alias module:model/IoK8sApiFlowcontrolV1beta3LimitResponse
     * @param type {String} `type` is \"Queue\" or \"Reject\". \"Queue\" means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. \"Reject\" means that requests that can not be executed upon arrival are rejected. Required.
     */
    constructor(type) { 
        
        IoK8sApiFlowcontrolV1beta3LimitResponse.initialize(this, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type) { 
        obj['type'] = type;
    }

    /**
     * Constructs a <code>IoK8sApiFlowcontrolV1beta3LimitResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiFlowcontrolV1beta3LimitResponse} obj Optional instance to populate.
     * @return {module:model/IoK8sApiFlowcontrolV1beta3LimitResponse} The populated <code>IoK8sApiFlowcontrolV1beta3LimitResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiFlowcontrolV1beta3LimitResponse();

            if (data.hasOwnProperty('queuing')) {
                obj['queuing'] = IoK8sApiFlowcontrolV1beta3QueuingConfiguration.constructFromObject(data['queuing']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiFlowcontrolV1beta3LimitResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiFlowcontrolV1beta3LimitResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApiFlowcontrolV1beta3LimitResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `queuing`
        if (data['queuing']) { // data not null
          IoK8sApiFlowcontrolV1beta3QueuingConfiguration.validateJSON(data['queuing']);
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

IoK8sApiFlowcontrolV1beta3LimitResponse.RequiredProperties = ["type"];

/**
 * @member {module:model/IoK8sApiFlowcontrolV1beta3QueuingConfiguration} queuing
 */
IoK8sApiFlowcontrolV1beta3LimitResponse.prototype['queuing'] = undefined;

/**
 * `type` is \"Queue\" or \"Reject\". \"Queue\" means that requests that can not be executed upon arrival are held in a queue until they can be executed or a queuing limit is reached. \"Reject\" means that requests that can not be executed upon arrival are rejected. Required.
 * @member {String} type
 */
IoK8sApiFlowcontrolV1beta3LimitResponse.prototype['type'] = undefined;






export default IoK8sApiFlowcontrolV1beta3LimitResponse;

