/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IoK8sApiCoreV1DaemonEndpoint model module.
 * @module model/IoK8sApiCoreV1DaemonEndpoint
 * @version v1.30.0
 */
class IoK8sApiCoreV1DaemonEndpoint {
    /**
     * Constructs a new <code>IoK8sApiCoreV1DaemonEndpoint</code>.
     * DaemonEndpoint contains information about a single Daemon endpoint.
     * @alias module:model/IoK8sApiCoreV1DaemonEndpoint
     * @param port {Number} Port number of the given endpoint.
     */
    constructor(port) { 
        
        IoK8sApiCoreV1DaemonEndpoint.initialize(this, port);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, port) { 
        obj['Port'] = port;
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1DaemonEndpoint</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1DaemonEndpoint} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1DaemonEndpoint} The populated <code>IoK8sApiCoreV1DaemonEndpoint</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1DaemonEndpoint();

            if (data.hasOwnProperty('Port')) {
                obj['Port'] = ApiClient.convertToType(data['Port'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1DaemonEndpoint</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1DaemonEndpoint</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApiCoreV1DaemonEndpoint.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

IoK8sApiCoreV1DaemonEndpoint.RequiredProperties = ["Port"];

/**
 * Port number of the given endpoint.
 * @member {Number} Port
 */
IoK8sApiCoreV1DaemonEndpoint.prototype['Port'] = undefined;






export default IoK8sApiCoreV1DaemonEndpoint;

