/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiCoreV1ScopedResourceSelectorRequirement from './IoK8sApiCoreV1ScopedResourceSelectorRequirement';

/**
 * The IoK8sApiCoreV1ScopeSelector model module.
 * @module model/IoK8sApiCoreV1ScopeSelector
 * @version v1.30.0
 */
class IoK8sApiCoreV1ScopeSelector {
    /**
     * Constructs a new <code>IoK8sApiCoreV1ScopeSelector</code>.
     * A scope selector represents the AND of the selectors represented by the scoped-resource selector requirements.
     * @alias module:model/IoK8sApiCoreV1ScopeSelector
     */
    constructor() { 
        
        IoK8sApiCoreV1ScopeSelector.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiCoreV1ScopeSelector</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiCoreV1ScopeSelector} obj Optional instance to populate.
     * @return {module:model/IoK8sApiCoreV1ScopeSelector} The populated <code>IoK8sApiCoreV1ScopeSelector</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiCoreV1ScopeSelector();

            if (data.hasOwnProperty('matchExpressions')) {
                obj['matchExpressions'] = ApiClient.convertToType(data['matchExpressions'], [IoK8sApiCoreV1ScopedResourceSelectorRequirement]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiCoreV1ScopeSelector</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiCoreV1ScopeSelector</code>.
     */
    static validateJSON(data) {
        if (data['matchExpressions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['matchExpressions'])) {
                throw new Error("Expected the field `matchExpressions` to be an array in the JSON data but got " + data['matchExpressions']);
            }
            // validate the optional field `matchExpressions` (array)
            for (const item of data['matchExpressions']) {
                IoK8sApiCoreV1ScopedResourceSelectorRequirement.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * A list of scope selector requirements by scope of the resources.
 * @member {Array.<module:model/IoK8sApiCoreV1ScopedResourceSelectorRequirement>} matchExpressions
 */
IoK8sApiCoreV1ScopeSelector.prototype['matchExpressions'] = undefined;






export default IoK8sApiCoreV1ScopeSelector;

