/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApimachineryPkgApisMetaV1APIGroup from './IoK8sApimachineryPkgApisMetaV1APIGroup';

/**
 * The IoK8sApimachineryPkgApisMetaV1APIGroupList model module.
 * @module model/IoK8sApimachineryPkgApisMetaV1APIGroupList
 * @version v1.30.0
 */
class IoK8sApimachineryPkgApisMetaV1APIGroupList {
    /**
     * Constructs a new <code>IoK8sApimachineryPkgApisMetaV1APIGroupList</code>.
     * APIGroupList is a list of APIGroup, to allow clients to discover the API at /apis.
     * @alias module:model/IoK8sApimachineryPkgApisMetaV1APIGroupList
     * @param groups {Array.<module:model/IoK8sApimachineryPkgApisMetaV1APIGroup>} groups is a list of APIGroup.
     */
    constructor(groups) { 
        
        IoK8sApimachineryPkgApisMetaV1APIGroupList.initialize(this, groups);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, groups) { 
        obj['groups'] = groups;
    }

    /**
     * Constructs a <code>IoK8sApimachineryPkgApisMetaV1APIGroupList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApimachineryPkgApisMetaV1APIGroupList} obj Optional instance to populate.
     * @return {module:model/IoK8sApimachineryPkgApisMetaV1APIGroupList} The populated <code>IoK8sApimachineryPkgApisMetaV1APIGroupList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApimachineryPkgApisMetaV1APIGroupList();

            if (data.hasOwnProperty('apiVersion')) {
                obj['apiVersion'] = ApiClient.convertToType(data['apiVersion'], 'String');
            }
            if (data.hasOwnProperty('groups')) {
                obj['groups'] = ApiClient.convertToType(data['groups'], [IoK8sApimachineryPkgApisMetaV1APIGroup]);
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApimachineryPkgApisMetaV1APIGroupList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApimachineryPkgApisMetaV1APIGroupList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApimachineryPkgApisMetaV1APIGroupList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['apiVersion'] && !(typeof data['apiVersion'] === 'string' || data['apiVersion'] instanceof String)) {
            throw new Error("Expected the field `apiVersion` to be a primitive type in the JSON string but got " + data['apiVersion']);
        }
        if (data['groups']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['groups'])) {
                throw new Error("Expected the field `groups` to be an array in the JSON data but got " + data['groups']);
            }
            // validate the optional field `groups` (array)
            for (const item of data['groups']) {
                IoK8sApimachineryPkgApisMetaV1APIGroup.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }

        return true;
    }


}

IoK8sApimachineryPkgApisMetaV1APIGroupList.RequiredProperties = ["groups"];

/**
 * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
 * @member {String} apiVersion
 */
IoK8sApimachineryPkgApisMetaV1APIGroupList.prototype['apiVersion'] = undefined;

/**
 * groups is a list of APIGroup.
 * @member {Array.<module:model/IoK8sApimachineryPkgApisMetaV1APIGroup>} groups
 */
IoK8sApimachineryPkgApisMetaV1APIGroupList.prototype['groups'] = undefined;

/**
 * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
 * @member {String} kind
 */
IoK8sApimachineryPkgApisMetaV1APIGroupList.prototype['kind'] = undefined;






export default IoK8sApimachineryPkgApisMetaV1APIGroupList;

