/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IoK8sApiAutoscalingV2MetricIdentifier from './IoK8sApiAutoscalingV2MetricIdentifier';
import IoK8sApiAutoscalingV2MetricTarget from './IoK8sApiAutoscalingV2MetricTarget';

/**
 * The IoK8sApiAutoscalingV2ExternalMetricSource model module.
 * @module model/IoK8sApiAutoscalingV2ExternalMetricSource
 * @version v1.30.0
 */
class IoK8sApiAutoscalingV2ExternalMetricSource {
    /**
     * Constructs a new <code>IoK8sApiAutoscalingV2ExternalMetricSource</code>.
     * ExternalMetricSource indicates how to scale on a metric not associated with any Kubernetes object (for example length of queue in cloud messaging service, or QPS from loadbalancer running outside of cluster).
     * @alias module:model/IoK8sApiAutoscalingV2ExternalMetricSource
     * @param metric {module:model/IoK8sApiAutoscalingV2MetricIdentifier} 
     * @param target {module:model/IoK8sApiAutoscalingV2MetricTarget} 
     */
    constructor(metric, target) { 
        
        IoK8sApiAutoscalingV2ExternalMetricSource.initialize(this, metric, target);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, metric, target) { 
        obj['metric'] = metric;
        obj['target'] = target;
    }

    /**
     * Constructs a <code>IoK8sApiAutoscalingV2ExternalMetricSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiAutoscalingV2ExternalMetricSource} obj Optional instance to populate.
     * @return {module:model/IoK8sApiAutoscalingV2ExternalMetricSource} The populated <code>IoK8sApiAutoscalingV2ExternalMetricSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiAutoscalingV2ExternalMetricSource();

            if (data.hasOwnProperty('metric')) {
                obj['metric'] = IoK8sApiAutoscalingV2MetricIdentifier.constructFromObject(data['metric']);
            }
            if (data.hasOwnProperty('target')) {
                obj['target'] = IoK8sApiAutoscalingV2MetricTarget.constructFromObject(data['target']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiAutoscalingV2ExternalMetricSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiAutoscalingV2ExternalMetricSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of IoK8sApiAutoscalingV2ExternalMetricSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `metric`
        if (data['metric']) { // data not null
          IoK8sApiAutoscalingV2MetricIdentifier.validateJSON(data['metric']);
        }
        // validate the optional field `target`
        if (data['target']) { // data not null
          IoK8sApiAutoscalingV2MetricTarget.validateJSON(data['target']);
        }

        return true;
    }


}

IoK8sApiAutoscalingV2ExternalMetricSource.RequiredProperties = ["metric", "target"];

/**
 * @member {module:model/IoK8sApiAutoscalingV2MetricIdentifier} metric
 */
IoK8sApiAutoscalingV2ExternalMetricSource.prototype['metric'] = undefined;

/**
 * @member {module:model/IoK8sApiAutoscalingV2MetricTarget} target
 */
IoK8sApiAutoscalingV2ExternalMetricSource.prototype['target'] = undefined;






export default IoK8sApiAutoscalingV2ExternalMetricSource;

