/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IoK8sApiStorageV1VolumeError model module.
 * @module model/IoK8sApiStorageV1VolumeError
 * @version v1.30.0
 */
class IoK8sApiStorageV1VolumeError {
    /**
     * Constructs a new <code>IoK8sApiStorageV1VolumeError</code>.
     * VolumeError captures an error encountered during a volume operation.
     * @alias module:model/IoK8sApiStorageV1VolumeError
     */
    constructor() { 
        
        IoK8sApiStorageV1VolumeError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IoK8sApiStorageV1VolumeError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IoK8sApiStorageV1VolumeError} obj Optional instance to populate.
     * @return {module:model/IoK8sApiStorageV1VolumeError} The populated <code>IoK8sApiStorageV1VolumeError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IoK8sApiStorageV1VolumeError();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>IoK8sApiStorageV1VolumeError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>IoK8sApiStorageV1VolumeError</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * message represents the error encountered during Attach or Detach operation. This string may be logged, so it should not contain sensitive information.
 * @member {String} message
 */
IoK8sApiStorageV1VolumeError.prototype['message'] = undefined;

/**
 * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
 * @member {Date} time
 */
IoK8sApiStorageV1VolumeError.prototype['time'] = undefined;






export default IoK8sApiStorageV1VolumeError;

