/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue model module.
 * @module model/ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue
 * @version v1.30.0
 */
class ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue {
    /**
     * Constructs a new <code>ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue</code>.
     * ResourceInfo is the sets about resource capacity and allocatable
     * @alias module:model/ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue
     */
    constructor() { 
        
        ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue} obj Optional instance to populate.
     * @return {module:model/ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue} The populated <code>ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue();

            if (data.hasOwnProperty('allocatable')) {
                obj['allocatable'] = ApiClient.convertToType(data['allocatable'], 'String');
            }
            if (data.hasOwnProperty('capacity')) {
                obj['capacity'] = ApiClient.convertToType(data['capacity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['allocatable'] && !(typeof data['allocatable'] === 'string' || data['allocatable'] instanceof String)) {
            throw new Error("Expected the field `allocatable` to be a primitive type in the JSON string but got " + data['allocatable']);
        }

        return true;
    }


}



/**
 * @member {String} allocatable
 */
ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue.prototype['allocatable'] = undefined;

/**
 * @member {Number} capacity
 */
ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue.prototype['capacity'] = undefined;






export default ShVolcanoNodeinfoV1alpha1NumatopologySpecNumaresValue;

