/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfigOptionsInner from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfigOptionsInner';

/**
 * The ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig model module.
 * @module model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig
 * @version v1.30.0
 */
class ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig {
    /**
     * Constructs a new <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig</code>.
     * @alias module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig
     */
    constructor() { 
        
        ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig} obj Optional instance to populate.
     * @return {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig} The populated <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig();

            if (data.hasOwnProperty('nameservers')) {
                obj['nameservers'] = ApiClient.convertToType(data['nameservers'], ['String']);
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfigOptionsInner]);
            }
            if (data.hasOwnProperty('searches')) {
                obj['searches'] = ApiClient.convertToType(data['searches'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['nameservers'])) {
            throw new Error("Expected the field `nameservers` to be an array in the JSON data but got " + data['nameservers']);
        }
        if (data['options']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['options'])) {
                throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
            }
            // validate the optional field `options` (array)
            for (const item of data['options']) {
                ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfigOptionsInner.validateJSON(item);
            };
        }
        // ensure the json data is an array
        if (!Array.isArray(data['searches'])) {
            throw new Error("Expected the field `searches` to be an array in the JSON data but got " + data['searches']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} nameservers
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig.prototype['nameservers'] = undefined;

/**
 * @member {Array.<module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfigOptionsInner>} options
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig.prototype['options'] = undefined;

/**
 * @member {Array.<String>} searches
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig.prototype['searches'] = undefined;






export default ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecDnsConfig;

