/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecContainersInnerLifecyclePostStartHttpGetHttpHeadersInner from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecContainersInnerLifecyclePostStartHttpGetHttpHeadersInner';

/**
 * The ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner model module.
 * @module model/ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner
 * @version v1.30.0
 */
class ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner {
    /**
     * Constructs a new <code>ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner</code>.
     * @alias module:model/ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner
     */
    constructor() { 
        
        ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner} obj Optional instance to populate.
     * @return {module:model/ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner} The populated <code>ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner();

            if (data.hasOwnProperty('httpHeader')) {
                obj['httpHeader'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecContainersInnerLifecyclePostStartHttpGetHttpHeadersInner.constructFromObject(data['httpHeader']);
            }
            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('port')) {
                obj['port'] = ApiClient.convertToType(data['port'], 'Number');
            }
            if (data.hasOwnProperty('taskName')) {
                obj['taskName'] = ApiClient.convertToType(data['taskName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner</code>.
     */
    static validateJSON(data) {
        // validate the optional field `httpHeader`
        if (data['httpHeader']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecContainersInnerLifecyclePostStartHttpGetHttpHeadersInner.validateJSON(data['httpHeader']);
        }
        // ensure the json data is a string
        if (data['path'] && !(typeof data['path'] === 'string' || data['path'] instanceof String)) {
            throw new Error("Expected the field `path` to be a primitive type in the JSON string but got " + data['path']);
        }
        // ensure the json data is a string
        if (data['taskName'] && !(typeof data['taskName'] === 'string' || data['taskName'] instanceof String)) {
            throw new Error("Expected the field `taskName` to be a primitive type in the JSON string but got " + data['taskName']);
        }

        return true;
    }


}



/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecContainersInnerLifecyclePostStartHttpGetHttpHeadersInner} httpHeader
 */
ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner.prototype['httpHeader'] = undefined;

/**
 * @member {String} path
 */
ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner.prototype['path'] = undefined;

/**
 * @member {Number} port
 */
ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner.prototype['port'] = undefined;

/**
 * @member {String} taskName
 */
ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner.prototype['taskName'] = undefined;






export default ShVolcanoFlowV1alpha1JobFlowSpecFlowsInnerDependsOnProbeHttpGetListInner;

