/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAwsElasticBlockStore from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAwsElasticBlockStore';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureDisk from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureDisk';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureFile from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureFile';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCephfs from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCephfs';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCinder from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCinder';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerConfigMap from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerConfigMap';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCsi from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCsi';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerDownwardAPI from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerDownwardAPI';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEmptyDir from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEmptyDir';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEphemeral from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEphemeral';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFc from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFc';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlexVolume from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlexVolume';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlocker from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlocker';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGcePersistentDisk from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGcePersistentDisk';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGitRepo from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGitRepo';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGlusterfs from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGlusterfs';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerHostPath from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerHostPath';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerIscsi from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerIscsi';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerNfs from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerNfs';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPersistentVolumeClaim from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPersistentVolumeClaim';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPhotonPersistentDisk from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPhotonPersistentDisk';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPortworxVolume from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPortworxVolume';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerProjected from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerProjected';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerQuobyte from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerQuobyte';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerRbd from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerRbd';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerScaleIO from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerScaleIO';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerSecret from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerSecret';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerStorageos from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerStorageos';
import ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerVsphereVolume from './ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerVsphereVolume';

/**
 * The ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner model module.
 * @module model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner
 * @version v1.30.0
 */
class ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner {
    /**
     * Constructs a new <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner</code>.
     * @alias module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner
     * @param name {String} 
     */
    constructor(name) { 
        
        ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner} obj Optional instance to populate.
     * @return {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner} The populated <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner();

            if (data.hasOwnProperty('awsElasticBlockStore')) {
                obj['awsElasticBlockStore'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAwsElasticBlockStore.constructFromObject(data['awsElasticBlockStore']);
            }
            if (data.hasOwnProperty('azureDisk')) {
                obj['azureDisk'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureDisk.constructFromObject(data['azureDisk']);
            }
            if (data.hasOwnProperty('azureFile')) {
                obj['azureFile'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureFile.constructFromObject(data['azureFile']);
            }
            if (data.hasOwnProperty('cephfs')) {
                obj['cephfs'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCephfs.constructFromObject(data['cephfs']);
            }
            if (data.hasOwnProperty('cinder')) {
                obj['cinder'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCinder.constructFromObject(data['cinder']);
            }
            if (data.hasOwnProperty('configMap')) {
                obj['configMap'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerConfigMap.constructFromObject(data['configMap']);
            }
            if (data.hasOwnProperty('csi')) {
                obj['csi'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCsi.constructFromObject(data['csi']);
            }
            if (data.hasOwnProperty('downwardAPI')) {
                obj['downwardAPI'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerDownwardAPI.constructFromObject(data['downwardAPI']);
            }
            if (data.hasOwnProperty('emptyDir')) {
                obj['emptyDir'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEmptyDir.constructFromObject(data['emptyDir']);
            }
            if (data.hasOwnProperty('ephemeral')) {
                obj['ephemeral'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEphemeral.constructFromObject(data['ephemeral']);
            }
            if (data.hasOwnProperty('fc')) {
                obj['fc'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFc.constructFromObject(data['fc']);
            }
            if (data.hasOwnProperty('flexVolume')) {
                obj['flexVolume'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlexVolume.constructFromObject(data['flexVolume']);
            }
            if (data.hasOwnProperty('flocker')) {
                obj['flocker'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlocker.constructFromObject(data['flocker']);
            }
            if (data.hasOwnProperty('gcePersistentDisk')) {
                obj['gcePersistentDisk'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGcePersistentDisk.constructFromObject(data['gcePersistentDisk']);
            }
            if (data.hasOwnProperty('gitRepo')) {
                obj['gitRepo'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGitRepo.constructFromObject(data['gitRepo']);
            }
            if (data.hasOwnProperty('glusterfs')) {
                obj['glusterfs'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGlusterfs.constructFromObject(data['glusterfs']);
            }
            if (data.hasOwnProperty('hostPath')) {
                obj['hostPath'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerHostPath.constructFromObject(data['hostPath']);
            }
            if (data.hasOwnProperty('iscsi')) {
                obj['iscsi'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerIscsi.constructFromObject(data['iscsi']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nfs')) {
                obj['nfs'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerNfs.constructFromObject(data['nfs']);
            }
            if (data.hasOwnProperty('persistentVolumeClaim')) {
                obj['persistentVolumeClaim'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPersistentVolumeClaim.constructFromObject(data['persistentVolumeClaim']);
            }
            if (data.hasOwnProperty('photonPersistentDisk')) {
                obj['photonPersistentDisk'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPhotonPersistentDisk.constructFromObject(data['photonPersistentDisk']);
            }
            if (data.hasOwnProperty('portworxVolume')) {
                obj['portworxVolume'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPortworxVolume.constructFromObject(data['portworxVolume']);
            }
            if (data.hasOwnProperty('projected')) {
                obj['projected'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerProjected.constructFromObject(data['projected']);
            }
            if (data.hasOwnProperty('quobyte')) {
                obj['quobyte'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerQuobyte.constructFromObject(data['quobyte']);
            }
            if (data.hasOwnProperty('rbd')) {
                obj['rbd'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerRbd.constructFromObject(data['rbd']);
            }
            if (data.hasOwnProperty('scaleIO')) {
                obj['scaleIO'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerScaleIO.constructFromObject(data['scaleIO']);
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerSecret.constructFromObject(data['secret']);
            }
            if (data.hasOwnProperty('storageos')) {
                obj['storageos'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerStorageos.constructFromObject(data['storageos']);
            }
            if (data.hasOwnProperty('vsphereVolume')) {
                obj['vsphereVolume'] = ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerVsphereVolume.constructFromObject(data['vsphereVolume']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `awsElasticBlockStore`
        if (data['awsElasticBlockStore']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAwsElasticBlockStore.validateJSON(data['awsElasticBlockStore']);
        }
        // validate the optional field `azureDisk`
        if (data['azureDisk']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureDisk.validateJSON(data['azureDisk']);
        }
        // validate the optional field `azureFile`
        if (data['azureFile']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureFile.validateJSON(data['azureFile']);
        }
        // validate the optional field `cephfs`
        if (data['cephfs']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCephfs.validateJSON(data['cephfs']);
        }
        // validate the optional field `cinder`
        if (data['cinder']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCinder.validateJSON(data['cinder']);
        }
        // validate the optional field `configMap`
        if (data['configMap']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerConfigMap.validateJSON(data['configMap']);
        }
        // validate the optional field `csi`
        if (data['csi']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCsi.validateJSON(data['csi']);
        }
        // validate the optional field `downwardAPI`
        if (data['downwardAPI']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerDownwardAPI.validateJSON(data['downwardAPI']);
        }
        // validate the optional field `emptyDir`
        if (data['emptyDir']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEmptyDir.validateJSON(data['emptyDir']);
        }
        // validate the optional field `ephemeral`
        if (data['ephemeral']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEphemeral.validateJSON(data['ephemeral']);
        }
        // validate the optional field `fc`
        if (data['fc']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFc.validateJSON(data['fc']);
        }
        // validate the optional field `flexVolume`
        if (data['flexVolume']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlexVolume.validateJSON(data['flexVolume']);
        }
        // validate the optional field `flocker`
        if (data['flocker']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlocker.validateJSON(data['flocker']);
        }
        // validate the optional field `gcePersistentDisk`
        if (data['gcePersistentDisk']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGcePersistentDisk.validateJSON(data['gcePersistentDisk']);
        }
        // validate the optional field `gitRepo`
        if (data['gitRepo']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGitRepo.validateJSON(data['gitRepo']);
        }
        // validate the optional field `glusterfs`
        if (data['glusterfs']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGlusterfs.validateJSON(data['glusterfs']);
        }
        // validate the optional field `hostPath`
        if (data['hostPath']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerHostPath.validateJSON(data['hostPath']);
        }
        // validate the optional field `iscsi`
        if (data['iscsi']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerIscsi.validateJSON(data['iscsi']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `nfs`
        if (data['nfs']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerNfs.validateJSON(data['nfs']);
        }
        // validate the optional field `persistentVolumeClaim`
        if (data['persistentVolumeClaim']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPersistentVolumeClaim.validateJSON(data['persistentVolumeClaim']);
        }
        // validate the optional field `photonPersistentDisk`
        if (data['photonPersistentDisk']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPhotonPersistentDisk.validateJSON(data['photonPersistentDisk']);
        }
        // validate the optional field `portworxVolume`
        if (data['portworxVolume']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPortworxVolume.validateJSON(data['portworxVolume']);
        }
        // validate the optional field `projected`
        if (data['projected']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerProjected.validateJSON(data['projected']);
        }
        // validate the optional field `quobyte`
        if (data['quobyte']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerQuobyte.validateJSON(data['quobyte']);
        }
        // validate the optional field `rbd`
        if (data['rbd']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerRbd.validateJSON(data['rbd']);
        }
        // validate the optional field `scaleIO`
        if (data['scaleIO']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerScaleIO.validateJSON(data['scaleIO']);
        }
        // validate the optional field `secret`
        if (data['secret']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerSecret.validateJSON(data['secret']);
        }
        // validate the optional field `storageos`
        if (data['storageos']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerStorageos.validateJSON(data['storageos']);
        }
        // validate the optional field `vsphereVolume`
        if (data['vsphereVolume']) { // data not null
          ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerVsphereVolume.validateJSON(data['vsphereVolume']);
        }

        return true;
    }


}

ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.RequiredProperties = ["name"];

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAwsElasticBlockStore} awsElasticBlockStore
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['awsElasticBlockStore'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureDisk} azureDisk
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['azureDisk'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerAzureFile} azureFile
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['azureFile'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCephfs} cephfs
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['cephfs'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCinder} cinder
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['cinder'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerConfigMap} configMap
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['configMap'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerCsi} csi
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['csi'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerDownwardAPI} downwardAPI
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['downwardAPI'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEmptyDir} emptyDir
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['emptyDir'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerEphemeral} ephemeral
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['ephemeral'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFc} fc
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['fc'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlexVolume} flexVolume
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['flexVolume'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerFlocker} flocker
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['flocker'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGcePersistentDisk} gcePersistentDisk
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['gcePersistentDisk'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGitRepo} gitRepo
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['gitRepo'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerGlusterfs} glusterfs
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['glusterfs'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerHostPath} hostPath
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['hostPath'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerIscsi} iscsi
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['iscsi'] = undefined;

/**
 * @member {String} name
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['name'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerNfs} nfs
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['nfs'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPersistentVolumeClaim} persistentVolumeClaim
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['persistentVolumeClaim'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPhotonPersistentDisk} photonPersistentDisk
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['photonPersistentDisk'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerPortworxVolume} portworxVolume
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['portworxVolume'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerProjected} projected
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['projected'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerQuobyte} quobyte
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['quobyte'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerRbd} rbd
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['rbd'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerScaleIO} scaleIO
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['scaleIO'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerSecret} secret
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['secret'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerStorageos} storageos
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['storageos'] = undefined;

/**
 * @member {module:model/ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInnerVsphereVolume} vsphereVolume
 */
ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner.prototype['vsphereVolume'] = undefined;






export default ShVolcanoBatchV1alpha1JobSpecTasksInnerTemplateSpecVolumesInner;

